# PR Labeler Configuration

# Bot core changes
bot:
  - changed-files:
      - any-glob-to-any-file: 'index.js'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

# CI/CD changes
ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'

# Website/Frontend
website:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*.html'
          - 'docs/**/*.css'
          - 'docs/**/*.js'

# Configuration
config:
  - changed-files:
      - any-glob-to-any-file:
          - '.env.example'
          - '*.json'
          - '*.yml'
          - '*.yaml'
